"""add due_date to instructional material

Revision ID: 10e53fe33367
Revises: 0d52f3dc7509
Create Date: 2025-11-02 17:28:07.522581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e53fe33367'
down_revision = '0d52f3dc7509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructionalmaterials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructionalmaterials', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
