"""subject_department table added

Revision ID: 21538961b26a
Revises: 20e8f1beda85
Create Date: 2025-09-09 21:38:07.208591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21538961b26a'
down_revision = '20e8f1beda85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_departments',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'department_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_departments')
    # ### end Alembic commands ###
