"""Updare imerpimec table

Revision ID: 4f0e17d3d577
Revises: 8db4bc4d7010
Create Date: 2025-10-06 10:12:16.915885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0e17d3d577'
down_revision = '8db4bc4d7010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imerpimec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('a1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('a2', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('a3', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('a_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('a_subtotal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('b1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('b2', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('b3', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('b_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('b_subtotal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c2', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c3', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c4', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c5', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c6', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c7', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c8', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c9', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c10', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c_subtotal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('d1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('d2', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('d3', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('d_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('d_subtotal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('e1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('e2', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('e3', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('e_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('e_subtotal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('overall_comment', sa.Text(), nullable=True))
        batch_op.drop_column('d')
        batch_op.drop_column('b')
        batch_op.drop_column('a')
        batch_op.drop_column('c')
        batch_op.drop_column('e')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imerpimec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('e', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('c', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('a', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('b', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('d', sa.INTEGER(), nullable=False))
        batch_op.drop_column('overall_comment')
        batch_op.drop_column('total')
        batch_op.drop_column('e_subtotal')
        batch_op.drop_column('e_comment')
        batch_op.drop_column('e3')
        batch_op.drop_column('e2')
        batch_op.drop_column('e1')
        batch_op.drop_column('d_subtotal')
        batch_op.drop_column('d_comment')
        batch_op.drop_column('d3')
        batch_op.drop_column('d2')
        batch_op.drop_column('d1')
        batch_op.drop_column('c_subtotal')
        batch_op.drop_column('c_comment')
        batch_op.drop_column('c10')
        batch_op.drop_column('c9')
        batch_op.drop_column('c8')
        batch_op.drop_column('c7')
        batch_op.drop_column('c6')
        batch_op.drop_column('c5')
        batch_op.drop_column('c4')
        batch_op.drop_column('c3')
        batch_op.drop_column('c2')
        batch_op.drop_column('c1')
        batch_op.drop_column('b_subtotal')
        batch_op.drop_column('b_comment')
        batch_op.drop_column('b3')
        batch_op.drop_column('b2')
        batch_op.drop_column('b1')
        batch_op.drop_column('a_subtotal')
        batch_op.drop_column('a_comment')
        batch_op.drop_column('a3')
        batch_op.drop_column('a2')
        batch_op.drop_column('a1')

    # ### end Alembic commands ###
