"""Added Instructional Materials table

Revision ID: 801978ba764f
Revises: c780e8ef95d9
Create Date: 2025-08-25 18:15:27.675754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801978ba764f'
down_revision = 'c780e8ef95d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructionalmaterials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('im_type', sa.String(), nullable=False),
    sa.Column('university_im_id', sa.Integer(), nullable=True),
    sa.Column('service_im_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validity', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('s3_link', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service_im_id'], ['serviceims.id'], ),
    sa.ForeignKeyConstraint(['university_im_id'], ['universityims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructionalmaterials')
    # ### end Alembic commands ###
