"""Add IMCertificate model

Revision ID: 84785f7fe9d6
Revises: f1e2fd0c0c18
Create Date: 2026-02-21 14:33:32.701573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84785f7fe9d6'
down_revision = 'f1e2fd0c0c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('im_certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qr_id', sa.String(length=50), nullable=False),
    sa.Column('im_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('s3_link', sa.String(length=500), nullable=False),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['im_id'], ['instructionalmaterials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('im_certificates')
    # ### end Alembic commands ###
