"""Make s3_link nullable for assignment workflow

Revision ID: 9900b629f139
Revises: bb2d64bb48e4
Create Date: 2025-10-12 16:01:00.171324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9900b629f139'
down_revision = 'bb2d64bb48e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructionalmaterials', schema=None) as batch_op:
        batch_op.alter_column('s3_link',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructionalmaterials', schema=None) as batch_op:
        batch_op.alter_column('s3_link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
