"""Initial SQLite migration

Revision ID: f1e2fd0c0c18
Revises: 
Create Date: 2026-02-20 17:47:48.002959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e2fd0c0c18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('imerpimec',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a1', sa.Integer(), nullable=False),
    sa.Column('a2', sa.Integer(), nullable=False),
    sa.Column('a3', sa.Integer(), nullable=False),
    sa.Column('a_comment', sa.Text(), nullable=True),
    sa.Column('a_subtotal', sa.Integer(), nullable=False),
    sa.Column('b1', sa.Integer(), nullable=False),
    sa.Column('b2', sa.Integer(), nullable=False),
    sa.Column('b3', sa.Integer(), nullable=False),
    sa.Column('b_comment', sa.Text(), nullable=True),
    sa.Column('b_subtotal', sa.Integer(), nullable=False),
    sa.Column('c1', sa.Integer(), nullable=False),
    sa.Column('c2', sa.Integer(), nullable=False),
    sa.Column('c3', sa.Integer(), nullable=False),
    sa.Column('c4', sa.Integer(), nullable=False),
    sa.Column('c5', sa.Integer(), nullable=False),
    sa.Column('c6', sa.Integer(), nullable=False),
    sa.Column('c7', sa.Integer(), nullable=False),
    sa.Column('c8', sa.Integer(), nullable=False),
    sa.Column('c9', sa.Integer(), nullable=False),
    sa.Column('c10', sa.Integer(), nullable=False),
    sa.Column('c_comment', sa.Text(), nullable=True),
    sa.Column('c_subtotal', sa.Integer(), nullable=False),
    sa.Column('d1', sa.Integer(), nullable=False),
    sa.Column('d2', sa.Integer(), nullable=False),
    sa.Column('d3', sa.Integer(), nullable=False),
    sa.Column('d_comment', sa.Text(), nullable=True),
    sa.Column('d_subtotal', sa.Integer(), nullable=False),
    sa.Column('e1', sa.Integer(), nullable=False),
    sa.Column('e2', sa.Integer(), nullable=False),
    sa.Column('e3', sa.Integer(), nullable=False),
    sa.Column('e_comment', sa.Text(), nullable=True),
    sa.Column('e_subtotal', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('overall_comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('staff_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('activitylog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collegesincluded',
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('college_id', 'user_id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('serviceims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departmentsincluded',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('department_id', 'user_id')
    )
    op.create_table('subject_departments',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'department_id')
    )
    op.create_table('universityims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructionalmaterials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('im_type', sa.String(length=50), nullable=False),
    sa.Column('university_im_id', sa.Integer(), nullable=True),
    sa.Column('service_im_id', sa.Integer(), nullable=True),
    sa.Column('imerpimec_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('validity', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('s3_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('published', sa.Integer(), nullable=False),
    sa.Column('utldo_attempt', sa.Integer(), nullable=False),
    sa.Column('pimec_attempt', sa.Integer(), nullable=False),
    sa.Column('ai_attempt', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['imerpimec_id'], ['imerpimec.id'], ),
    sa.ForeignKeyConstraint(['service_im_id'], ['serviceims.id'], ),
    sa.ForeignKeyConstraint(['university_im_id'], ['universityims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors',
    sa.Column('im_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['im_id'], ['instructionalmaterials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('im_id', 'user_id')
    )
    op.create_table('im_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('im_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['im_id'], ['instructionalmaterials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('im_submissions')
    op.drop_table('authors')
    op.drop_table('instructionalmaterials')
    op.drop_table('universityims')
    op.drop_table('subject_departments')
    op.drop_table('departmentsincluded')
    op.drop_table('serviceims')
    op.drop_table('departments')
    op.drop_table('collegesincluded')
    op.drop_table('activitylog')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('imerpimec')
    op.drop_table('colleges')
    # ### end Alembic commands ###
