from .auth import *
from .user import *
from .department import *
from .college import *
from .subject import *
from .universityim import *
from .serviceim import *
from .collegeincluded import *
from .instructionalmaterial import *
from .author import *
from .subject_department import *
from .imerpimec import *